### ISSUE TITLE
T1 - Página de inicio

### ISSUE THREAD

**Issue by tomgalbar** [ISPP-2022/housekeeping#14]
### Tarea T1 - Página de inicio:

**Actividades del Backend:**
- [x] Stacking-Up/infrastructure#1

**Actividades del Frontend:**
- [x] Stacking-Up/frontend#5
- [x] Stacking-Up/frontend#6
- [x] Stacking-Up/frontend#7
- [x] Stacking-Up/frontend#8
