### ISSUE TITLE
T19 - Suscripciones

### ISSUE THREAD

**Issue by carlosatyca** [ISPP-2022/housekeeping#142]
### Tarea T19 - Suscripciones:

**Actividades del Backend:**
- [ ] Stacking-Up/auth-service#20
- [ ] Stacking-Up/data-service#54

**Actividades del Frontend:**
- [ ] Stacking-Up/frontend#148
