### ISSUE TITLE
R1 - Refactorización, deuda técnica y correcciones en la lógica para la posterior implementación del pago

### ISSUE THREAD

**Issue by tomgalbar** [ISPP-2022/housekeeping#171]
### Refactorización, deuda técnica y correcciones en la lógica para la posterior implementación del pago

**Actividades**
- [x] Stacking-Up/frontend#122
- [ ] Stacking-Up/data-service#40
- [ ] Stacking-Up/data-service#39
- [ ] Stacking-Up/frontend#124
