### ISSUE TITLE
F1 - Feedback

### ISSUE THREAD

**Issue by tomgalbar** [ISPP-2022/housekeeping#176]
### Feedback

**Actividades**
- [ ] Stacking-Up/frontend#125
- [ ] Stacking-Up/data-service#41
- [ ] Stacking-Up/frontend#126
