### ISSUE TITLE
T2 - Inicio de sesión

### ISSUE THREAD

**Issue by carlosatyca** [ISPP-2022/housekeeping#20]
### Tarea T2 - Inicio de sesión:

**Actividades del Backend:**
- [x] Stacking-Up/data-service#1
- [x] Stacking-Up/auth-service#8
- [x] Stacking-Up/data-service#4
- [x] Stacking-Up/auth-service#1
- [x] Stacking-Up/auth-service#2
- [x] Stacking-Up/auth-service#3
- [x] Stacking-Up/auth-service#4

**Actividades del Frontend:**
- [x] Stacking-Up/frontend#10
- [x] Stacking-Up/frontend#11
- [ ] Stacking-Up/frontend#12
- [x] Stacking-Up/frontend#13
