### ISSUE TITLE
T3 - Detalles del espacio

### ISSUE THREAD

**Issue by tomgalbar** [ISPP-2022/housekeeping#35]
### Tarea T3 - Detalles del espacio:

**Actividades del Backend:**
- [x] Stacking-Up/data-service#5
- [x] Stacking-Up/data-service#6
- [x] Stacking-Up/data-service#7
- [x] Stacking-Up/data-service#8
- [x] Stacking-Up/data-service#9

**Actividades del Frontend:**
- [x] Stacking-Up/frontend#18
- [x] Stacking-Up/frontend#20
- [x] Stacking-Up/frontend#21
- [x] Stacking-Up/frontend#24
