### ISSUE TITLE
T4 - Barra de búsqueda

### ISSUE THREAD

**Issue by carlosatyca** [ISPP-2022/housekeeping#44]
### Tarea T4 - Barra de búsqueda:

**Actividades del Backend:**
- [x] Stacking-Up/data-service#10
- [x] Stacking-Up/data-service#11

**Actividades del Frontend:**
- [x] Stacking-Up/frontend#17
- [x] Stacking-Up/frontend#19
