### ISSUE TITLE
T5 - Filtros y etiquetas

### ISSUE THREAD

**Issue by carlosatyca** [ISPP-2022/housekeeping#56]
### Tarea T5 - Filtros y etiquetas:

**Actividades del Backend:**
- [x] Stacking-Up/data-service#12
- [x] Stacking-Up/data-service#13
- [x] Stacking-Up/data-service#14

**Actividades del Frontend:**
- [x] Stacking-Up/frontend#26
- [x] Stacking-Up/frontend#27
- [x] Stacking-Up/frontend#28
