### ISSUE TITLE
T6 - Búsqueda inteligente

### ISSUE THREAD

**Issue by tomgalbar** [ISPP-2022/housekeeping#57]
### Tarea T6 - Búsqueda inteligente:

**Actividades del Backend:**
- [x] Stacking-Up/data-service#15
- [x] Stacking-Up/data-service#16
- [x] Stacking-Up/data-service#18

**Actividades del Frontend:**
- [x] Stacking-Up/frontend#30
- [x] Stacking-Up/frontend#31
- [x] Stacking-Up/frontend#32
- [x] Stacking-Up/frontend#33
- [x] Stacking-Up/frontend#34
