### ISSUE TITLE
T7 - Publicación y modificación de anuncios

### ISSUE THREAD

**Issue by tomgalbar** [ISPP-2022/housekeeping#75]
### Tarea T7 - Publicación y modificación de anuncios:

**Actividades del Backend:**
- [x] Stacking-Up/data-service#19
- [x] Stacking-Up/data-service#20

**Actividades del Frontend:**
- [x] Stacking-Up/frontend#36
- [x] Stacking-Up/frontend#37
- [x] Stacking-Up/frontend#38
- [x] Stacking-Up/frontend#39
- [x] Stacking-Up/frontend#40
- [x] Stacking-Up/frontend#41
