### ISSUE TITLE
T8 - Alquiler/Reserva de espacios

### ISSUE THREAD

**Issue by tomgalbar** [ISPP-2022/housekeeping#85]
### Tarea T8 - Alquiler/Reserva de espacios:

**Actividades del Backend:**
- [x] Stacking-Up/data-service#21
- [x] Stacking-Up/data-service#22

**Actividades del Frontend:**
- [x] Stacking-Up/frontend#43
- [x] Stacking-Up/frontend#45
